// Chapter 1 is deliberately isolated from the published lesson player.
const scene = (id, image, title, enTitle, jp, en, hint, enHint, kind='tap', point=[50,52], extra={}) =>
  ({id,image,title,enTitle,jp,en,hint,enHint,kind,point,...extra});
window.AIKO_MORNING = [
 scene('sleep','sleeping.png','あたらしい朝','A new morning','今日は、あたらしい学校に行く日。\nでも、レンはまだ夢の中。','Today is Ren’s first day at his new school.\nBut Ren is still dreaming.','時計をタップして、はじめよう。','Tap the clock to begin.','tap',[76,49],{nextLabel:'はじめる',enNextLabel:'Begin'}),
 scene('alarm','sleeping.png','ジリリリッ！','Riiing!','「うーん……。まだ、ねむいよ。」','“Mmm… I’m still sleepy.”','時計をタップして、とめよう。','Tap the clock to stop the alarm.','alarm',[76,49]),
 scene('stop','stop-alarm.png','あと、すこしだけ','Just a little longer','レンは手をのばして、時計をとめた。\n「あと、すこしだけ……。」','Ren reaches out and stops the clock.\n“Just a little longer…”','レンの手をタップしよう。','Tap Ren’s hand.','tap',[69,48]),
 scene('snooze','sleeping-again.png','すやすや……','Back to sleep…','また、ねてしまった。\nあっという間に、７時５分。','He has fallen asleep again.\nSoon, it is 7:05.','時計をタップしよう。','Tap the clock.','tap',[76,49],{time:'7:05'}),
 scene('wake','waking.png','おはよう、レン！','Good morning, Ren!','「ふわぁ……。おきなくちゃ！」\nレンは目をこすった。','“Yaaawn… I need to get up!”\nRen rubs his eyes.','ふとんを下にスワイプしよう。','Swipe the blanket down.','swipe',[48,64],{actionLabel:'おきる',enActionLabel:'Get up',done:'「よし、おきた！」',enDone:'“Okay, I’m up!”'}),
 scene('bedroom-exit','pov-bedroom-exit.png','部屋を出よう','Leave the bedroom','まずは、歯をみがこう。\n部屋を出て、ろうかへ。','First, let’s brush our teeth.\nLeave the room and head into the hall.','通り道をタップしよう。','Tap the passage.','travel',[50,48]),
 scene('stairs-down','pov-stairs-down.png','階段をおりよう','Go downstairs','階段を、ゆっくりおりる。','Go down the stairs slowly.','階段をタップしよう。','Tap the stairs.','travel',[50,58]),
 scene('washroom','pov-washroom.png','洗面所へ','To the washroom','洗面所についた。\n歯ブラシは、どこかな？','We’re in the washroom.\nWhere is the toothbrush?','洗面台をタップしよう。','Tap the sink.','travel',[43,45]),
 scene('brush','brush-mess.png','しゃか、しゃか！','Brush, brush!','レンは、いそいで歯をみがく。\nあわが、口のまわりにいっぱい！','Ren brushes his teeth in a hurry.\nFoam is all around his mouth!','歯ブラシを左右に３回うごかそう。','Move the toothbrush side to side three times.','brush',[50,43],{count:3,actionLabel:'みがく',enActionLabel:'Brush',done:'「あれ？　あわの、ひげだ！」',enDone:'“Huh? A foam moustache!”'}),
 scene('wipe','brush-mess.png','あわだらけ！','Foam everywhere!','「あっ、洗面台にも！」\nタオルで、きれいにしよう。','“Oh! It’s on the sink, too!”\nLet’s clean it with a towel.','あわを３回ふいて、きれいにしよう。','Wipe the foam three times to clean up.','wipe',[48,61],{count:3,after:'brush-clean.png',actionLabel:'ふく',enActionLabel:'Wipe',done:'「ぴかぴか！　これで、よし。」',enDone:'“Sparkling clean! All done.”'}),
 scene('dining','pov-dining.png','朝ごはんだ！','Breakfast time!','お母さんの声がする。\n「レン、朝ごはんよ！」','Ren hears his mother calling.\n“Ren, breakfast is ready!”','テーブルをタップしよう。','Tap the table.','travel',[50,57]),
 scene('breakfast','breakfast.png','いただきます！','Let’s eat!','「いただきます！」\nレンは、もぐもぐ、ぱくぱく。','“Let’s eat!”\nRen munches his breakfast.','パン、たまご、飲みものをタップしよう。','Tap the toast, egg, and drink.','collect',[50,60],{after:'breakfast-done.png',items:[['パン','Toast','bread'],['たまご','Egg','egg'],['飲みもの','Drink','cup']],done:'「ごちそうさまでした！」',enDone:'“Thank you for the meal!”'}),
 scene('upstairs','pov-stairs-up.png','じゅんびをしよう','Time to get ready','おなかが、いっぱい。\n部屋にもどって、じゅんびをしよう。','His tummy is full.\nLet’s go back upstairs and get ready.','上の階へ進もう。','Head upstairs.','travel',[50,45]),
 scene('clothes','dressed.png','きがえたよ','Dressed for school','みどりの服に、こん色のズボン。\n「よし！　じゅんび、じゅんび！」','A green top and navy shorts.\n“Right! Time to get ready!”','服をタップして、たしかめよう。','Tap his clothes to get ready.','tap',[48,49]),
 scene('packing','packing.png','わすれものは、ない？','Have we got everything?','教科書と、ノートを入れよう。\n……あれ？　カエルも見ている。','Let’s pack the textbook and notebook.\n…Oh? The frog is watching, too.','教科書とノートを、かばんに入れよう。','Put the textbook and notebook into the bag.','pack',[63,67],{items:[['教科書','Textbook','book'],['ノート','Notebook','notebook']],done:'「これで、だいじょうぶ！」',enDone:'“That’s everything!”'}),
 scene('frog','packing.png','ひみつの、ともだち','A secret friend','「きみも、いっしょに行こう。\n……お母さんには、ひみつだよ。」','“You can come with me.\n…But don’t tell Mum.”','カエルを、かばんまでドラッグしよう。','Drag the frog into the bag.','frog',[63,67],{after:'packed.png',actionLabel:'カエルを入れる',enActionLabel:'Pack the frog',done:'「しーっ！」\nかばんの中で、ぴゅっ。',enDone:'“Shhh!”\nA tiny squeak comes from the bag.'}),
 scene('down-again','pov-stairs-down.png','さあ、出発！','Time to go!','かばんを持って、階段をおりる。\nカエルは、しずかにしているかな？','Bag in hand, Ren heads downstairs.\nIs the frog keeping quiet?','階段をタップしよう。','Tap the stairs.','travel',[50,58]),
 scene('genkan','pov-genkan.png','玄関へ','To the entrance','くつをはいたら、出発だ。','Once his shoes are on, it’s time to leave.','玄関をタップしよう。','Tap the entrance.','travel',[50,53]),
 scene('shoes','shoes.png','くつを、はこう','Put on your shoes','右のくつ、左のくつ。\nかばんも、わすれずに！','Right shoe, left shoe.\nDon’t forget the bag!','くつと、かばんをタップしよう。','Tap the shoes and the bag.','collect',[50,66],{items:[['右のくつ','Right shoe','shoe'],['左のくつ','Left shoe','shoe'],['かばん','Bag','bag']],done:'「いってきます！」\n「いってらっしゃい！」',enDone:'“I’m off!”\n“Have a good day!”'}),
 scene('end','shoes.png','第１章　おしまい','Chapter 1 complete','あたらしい一日が、はじまる。\nカエルも、こっそり、いっしょに。','A new day is beginning.\nAnd the frog is secretly coming along.','朝のものがたりを、ふりかえろう。','Look back through the morning story.','end',[50,52])
];
