import { Plus, Trash2 } from "lucide-react";
import type { GrammarPoint, LessonPackage, VocabularyItem } from "@/types/lesson";
import { EditorField, EditorPanel, inputClass } from "@/components/admin/lessons/editor-fields";
import { Button } from "@/components/ui/button";

export function CurriculumContentEditor({ lesson, errors, onChange }: { lesson: LessonPackage; errors: Record<string, string>; onChange: (lesson: LessonPackage) => void }) {
  return (
    <div className="space-y-6">
      <EditorPanel title="Curriculum links" description="Prerequisites and lesson tags." error={errors.grammar ?? errors.kanji ?? errors.vocabulary}>
        <EditorField label="Prerequisites (tags)"><input value={(lesson.tags ?? []).filter((tag) => tag.startsWith("prerequisite:")).map((tag) => tag.replace("prerequisite:", "")).join(", ")} onChange={(event) => onChange({ ...lesson, tags: [...(lesson.tags ?? []).filter((tag) => !tag.startsWith("prerequisite:")), ...event.target.value.split(",").map((item) => item.trim()).filter(Boolean).map((item) => `prerequisite:${item}`)] })} className={inputClass} /></EditorField>
      </EditorPanel>
      <EditorPanel title="Vocabulary" description="Written form, reading, meaning, part of speech, level, and example sentence." error={errors.vocabulary}>
        <div className="space-y-4">{lesson.vocabulary.map((item, index) => <VocabularyRow key={`${item.term}_${index}`} item={item} onChange={(next) => onChange({ ...lesson, vocabulary: lesson.vocabulary.map((current, itemIndex) => itemIndex === index ? next : current) })} onRemove={() => onChange({ ...lesson, vocabulary: lesson.vocabulary.filter((_, itemIndex) => itemIndex !== index) })} />)}</div>
        <Button type="button" variant="secondary" className="mt-4 rounded-xl" onClick={() => onChange({ ...lesson, vocabulary: [...lesson.vocabulary, { term: "", reading: "", meaning: "", partOfSpeech: "noun", level: lesson.level, exampleSentence: "" }] })}><Plus className="size-4" /> Add vocabulary</Button>
      </EditorPanel>
      <EditorPanel title="Grammar" description="Patterns, structure, usage, examples, and common mistakes." error={errors.grammar}>
        <div className="space-y-4">{lesson.grammar.map((item, index) => <GrammarRow key={item.id} item={item} onChange={(next) => onChange({ ...lesson, grammar: lesson.grammar.map((current, itemIndex) => itemIndex === index ? next : current) })} onRemove={() => onChange({ ...lesson, grammar: lesson.grammar.filter((_, itemIndex) => itemIndex !== index) })} />)}</div>
        <Button type="button" variant="secondary" className="mt-4 rounded-xl" onClick={() => onChange({ ...lesson, grammar: [...lesson.grammar, { id: `${lesson.id}_grammar_${lesson.grammar.length + 1}`, pattern: "", meaning: "", structure: "", usage: "", example: "", translation: "", commonMistake: "" }] })}><Plus className="size-4" /> Add grammar point</Button>
      </EditorPanel>
      <EditorPanel title="Kanji" description="Character, reading, and meaning." error={errors.kanji}>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{lesson.kanji.map((item, index) => <div key={`${item.character}_${index}`} className="rounded-xl border border-slate-200 p-4"><div className="grid grid-cols-3 gap-2"><input aria-label="Kanji character" value={item.character} onChange={(event) => onChange({ ...lesson, kanji: lesson.kanji.map((current, itemIndex) => itemIndex === index ? { ...current, character: event.target.value } : current) })} className={inputClass} /><input aria-label="Kanji reading" value={item.reading} onChange={(event) => onChange({ ...lesson, kanji: lesson.kanji.map((current, itemIndex) => itemIndex === index ? { ...current, reading: event.target.value } : current) })} className={inputClass} /><input aria-label="Kanji meaning" value={item.meaning} onChange={(event) => onChange({ ...lesson, kanji: lesson.kanji.map((current, itemIndex) => itemIndex === index ? { ...current, meaning: event.target.value } : current) })} className={inputClass} /></div><button type="button" className="mt-2 text-xs font-bold text-red-600" onClick={() => onChange({ ...lesson, kanji: lesson.kanji.filter((_, itemIndex) => itemIndex !== index) })}>Remove</button></div>)}</div>
        <Button type="button" variant="secondary" className="mt-4 rounded-xl" onClick={() => onChange({ ...lesson, kanji: [...lesson.kanji, { character: "", reading: "", meaning: "" }] })}><Plus className="size-4" /> Add kanji</Button>
      </EditorPanel>
    </div>
  );
}

function VocabularyRow({ item, onChange, onRemove }: { item: VocabularyItem; onChange: (item: VocabularyItem) => void; onRemove: () => void }) {
  return <div className="grid gap-3 rounded-xl border border-slate-200 p-4 sm:grid-cols-2 xl:grid-cols-6"><EditorField label="Written form"><input value={item.term} onChange={(event) => onChange({ ...item, term: event.target.value })} className={inputClass} /></EditorField><EditorField label="Reading"><input value={item.reading} onChange={(event) => onChange({ ...item, reading: event.target.value })} className={inputClass} /></EditorField><EditorField label="Meaning"><input value={item.meaning} onChange={(event) => onChange({ ...item, meaning: event.target.value })} className={inputClass} /></EditorField><EditorField label="Part of speech"><input value={item.partOfSpeech} onChange={(event) => onChange({ ...item, partOfSpeech: event.target.value })} className={inputClass} /></EditorField><EditorField label="Level"><select value={item.level ?? "N5"} onChange={(event) => onChange({ ...item, level: event.target.value as LessonPackage["level"] })} className={inputClass}>{["N5", "N4", "N3", "N2", "N1"].map((level) => <option key={level}>{level}</option>)}</select></EditorField><button type="button" aria-label="Remove vocabulary" onClick={onRemove} className="self-end grid min-h-11 place-items-center rounded-xl text-red-600 hover:bg-red-50"><Trash2 className="size-4" /></button><EditorField label="Example sentence" className="sm:col-span-2 xl:col-span-6"><input value={item.exampleSentence ?? ""} onChange={(event) => onChange({ ...item, exampleSentence: event.target.value })} className={inputClass} /></EditorField></div>;
}

function GrammarRow({ item, onChange, onRemove }: { item: GrammarPoint; onChange: (item: GrammarPoint) => void; onRemove: () => void }) {
  return <div className="grid gap-3 rounded-xl border border-slate-200 p-4 sm:grid-cols-2 xl:grid-cols-4"><EditorField label="Pattern"><input value={item.pattern} onChange={(event) => onChange({ ...item, pattern: event.target.value })} className={inputClass} /></EditorField><EditorField label="Meaning"><input value={item.meaning} onChange={(event) => onChange({ ...item, meaning: event.target.value })} className={inputClass} /></EditorField><EditorField label="Structure"><input value={item.structure} onChange={(event) => onChange({ ...item, structure: event.target.value })} className={inputClass} /></EditorField><button type="button" aria-label="Remove grammar" onClick={onRemove} className="self-end grid min-h-11 place-items-center rounded-xl text-red-600 hover:bg-red-50"><Trash2 className="size-4" /></button><EditorField label="Usage"><textarea value={item.usage} onChange={(event) => onChange({ ...item, usage: event.target.value })} className={`${inputClass} min-h-20 py-3`} /></EditorField><EditorField label="Example"><textarea value={item.example} onChange={(event) => onChange({ ...item, example: event.target.value })} className={`${inputClass} min-h-20 py-3`} /></EditorField><EditorField label="English example"><textarea value={item.translation} onChange={(event) => onChange({ ...item, translation: event.target.value })} className={`${inputClass} min-h-20 py-3`} /></EditorField><EditorField label="Common mistake"><textarea value={item.commonMistake} onChange={(event) => onChange({ ...item, commonMistake: event.target.value })} className={`${inputClass} min-h-20 py-3`} /></EditorField></div>;
}
