import { Plus, Trash2 } from "lucide-react";
import type { ChoiceExercise, ConversationLine, LessonPackage, SpeakingExercise } from "@/types/lesson";
import { EditorField, EditorPanel, inputClass } from "@/components/admin/lessons/editor-fields";
import { Button } from "@/components/ui/button";

export function ExerciseEditor({ lesson, errors, onChange }: { lesson: LessonPackage; errors: Record<string, string>; onChange: (lesson: LessonPackage) => void }) {
  return (
    <div className="space-y-6">
      <EditorPanel title="Reading" description="Dialogue speakers, tappable content, and expected reading sequence." error={errors.reading}>
        <div className="space-y-3">{lesson.readingConversation.map((line, index) => <ConversationRow key={`${line.speaker}_${index}`} line={line} onChange={(next) => onChange({ ...lesson, readingConversation: lesson.readingConversation.map((item, itemIndex) => itemIndex === index ? next : item) })} onRemove={() => onChange({ ...lesson, readingConversation: lesson.readingConversation.filter((_, itemIndex) => itemIndex !== index) })} />)}</div>
        <Button type="button" variant="secondary" className="mt-4 rounded-xl" onClick={() => onChange({ ...lesson, readingConversation: [...lesson.readingConversation, { speaker: "Speaker", japanese: "", english: "" }] })}><Plus className="size-4" /> Add dialogue line</Button>
      </EditorPanel>
      <ChoiceGroup title="Listening" description="Prompt, transcript context, choices, answer, explanation, and simulated audio." items={lesson.listeningExercises} error={errors.listening} onChange={(items) => onChange({ ...lesson, listeningExercises: items })} lessonId={lesson.id} mode="listening" />
      <EditorPanel title="Speaking" description="Easy, medium, and hard prompts plus expected and natural answers." error={errors.speaking}>
        <div className="space-y-4">{lesson.speakingExercises.map((item, index) => <SpeakingRow key={item.id} item={item} onChange={(next) => onChange({ ...lesson, speakingExercises: lesson.speakingExercises.map((current, itemIndex) => itemIndex === index ? next : current) })} onRemove={() => onChange({ ...lesson, speakingExercises: lesson.speakingExercises.filter((_, itemIndex) => itemIndex !== index) })} />)}</div>
        <Button type="button" variant="secondary" className="mt-4 rounded-xl" onClick={() => onChange({ ...lesson, speakingExercises: [...lesson.speakingExercises, { id: `${lesson.id}_speaking_${lesson.speakingExercises.length + 1}`, prompt: "", modelAnswer: "", mode: "medium", easyPrompt: "", mediumPrompt: "", hardPrompt: "", expectedAnswer: "" }] })}><Plus className="size-4" /> Add speaking activity</Button>
      </EditorPanel>
      <ChoiceGroup title="Final review" description="Question type, prompt, options, correct answer, and explanation." items={lesson.reviewQuestions} error={errors.review ?? errors.answerKeys} onChange={(items) => onChange({ ...lesson, reviewQuestions: items, answerKeys: items.map((item) => item.correctAnswer) })} lessonId={lesson.id} mode="review" />
    </div>
  );
}

function ConversationRow({ line, onChange, onRemove }: { line: ConversationLine; onChange: (line: ConversationLine) => void; onRemove: () => void }) {
  return <div className="grid gap-3 rounded-xl border border-slate-200 p-4 sm:grid-cols-[.5fr_1fr_1fr_auto]"><EditorField label="Speaker"><input value={line.speaker} onChange={(event) => onChange({ ...line, speaker: event.target.value })} className={inputClass} /></EditorField><EditorField label="Japanese"><textarea value={line.japanese} onChange={(event) => onChange({ ...line, japanese: event.target.value })} className={`${inputClass} min-h-20 py-3`} /></EditorField><EditorField label="Translation"><textarea value={line.english} onChange={(event) => onChange({ ...line, english: event.target.value })} className={`${inputClass} min-h-20 py-3`} /></EditorField><button type="button" aria-label="Remove reading line" onClick={onRemove} className="self-end grid min-h-11 place-items-center rounded-xl text-red-600 hover:bg-red-50"><Trash2 className="size-4" /></button></div>;
}

function ChoiceGroup({ title, description, items, error, onChange, lessonId, mode }: { title: string; description: string; items: ChoiceExercise[]; error?: string; onChange: (items: ChoiceExercise[]) => void; lessonId: string; mode: "listening" | "review" }) {
  return <EditorPanel title={title} description={description} error={error}><div className="space-y-4">{items.map((item, index) => <ChoiceRow key={item.id} item={item} mode={mode} onChange={(next) => onChange(items.map((current, itemIndex) => itemIndex === index ? next : current))} onRemove={() => onChange(items.filter((_, itemIndex) => itemIndex !== index))} />)}</div><Button type="button" variant="secondary" className="mt-4 rounded-xl" onClick={() => onChange([...items, { id: `${lessonId}_${title.toLowerCase().replaceAll(" ", "_")}_${items.length + 1}`, prompt: "", choices: ["", "", "", ""], correctAnswer: "", explanation: "", questionType: "multiple-choice", transcript: mode === "listening" ? "" : undefined, audioAssetId: mode === "listening" ? "" : undefined }])}><Plus className="size-4" /> Add {title.toLowerCase()} question</Button></EditorPanel>;
}

function ChoiceRow({ item, onChange, onRemove, mode }: { item: ChoiceExercise; onChange: (item: ChoiceExercise) => void; onRemove: () => void; mode: "listening" | "review" }) {
  return <div className="rounded-xl border border-slate-200 p-4"><div className="grid gap-3 sm:grid-cols-2"><EditorField label="Question type"><select value={item.questionType ?? "multiple-choice"} onChange={(event) => onChange({ ...item, questionType: event.target.value as ChoiceExercise["questionType"] })} className={inputClass}><option>multiple-choice</option><option>ordering</option><option>fill-blank</option><option>true-false</option></select></EditorField><EditorField label="Prompt"><input value={item.prompt} onChange={(event) => onChange({ ...item, prompt: event.target.value })} className={inputClass} /></EditorField>{mode === "listening" && <><EditorField label="Transcript"><textarea value={item.transcript ?? ""} onChange={(event) => onChange({ ...item, transcript: event.target.value })} className={`${inputClass} min-h-20 py-3`} lang="ja" /></EditorField><EditorField label="Simulated audio asset"><input value={item.audioAssetId ?? ""} onChange={(event) => onChange({ ...item, audioAssetId: event.target.value })} className={inputClass} /></EditorField></>}<EditorField label="Correct answer"><input value={item.correctAnswer} onChange={(event) => onChange({ ...item, correctAnswer: event.target.value })} className={inputClass} /></EditorField><EditorField label="Options (one per line)"><textarea value={item.choices.join("\n")} onChange={(event) => onChange({ ...item, choices: event.target.value.split("\n") })} className={`${inputClass} min-h-24 py-3`} /></EditorField><EditorField label="Explanation"><textarea value={item.explanation} onChange={(event) => onChange({ ...item, explanation: event.target.value })} className={`${inputClass} min-h-24 py-3`} /></EditorField></div><button type="button" onClick={onRemove} className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-red-600"><Trash2 className="size-4" /> Remove question</button></div>;
}

function SpeakingRow({ item, onChange, onRemove }: { item: SpeakingExercise; onChange: (item: SpeakingExercise) => void; onRemove: () => void }) {
  return <div className="grid gap-3 rounded-xl border border-slate-200 p-4 sm:grid-cols-2 xl:grid-cols-3"><EditorField label="Default prompt"><input value={item.prompt} onChange={(event) => onChange({ ...item, prompt: event.target.value })} className={inputClass} /></EditorField><EditorField label="Easy prompt"><input value={item.easyPrompt ?? ""} onChange={(event) => onChange({ ...item, easyPrompt: event.target.value })} className={inputClass} /></EditorField><EditorField label="Medium prompt"><input value={item.mediumPrompt ?? ""} onChange={(event) => onChange({ ...item, mediumPrompt: event.target.value })} className={inputClass} /></EditorField><EditorField label="Hard prompt"><input value={item.hardPrompt ?? ""} onChange={(event) => onChange({ ...item, hardPrompt: event.target.value })} className={inputClass} /></EditorField><EditorField label="Expected answer"><input value={item.expectedAnswer ?? ""} onChange={(event) => onChange({ ...item, expectedAnswer: event.target.value })} className={inputClass} /></EditorField><EditorField label="Suggested natural answer"><input value={item.modelAnswer} onChange={(event) => onChange({ ...item, modelAnswer: event.target.value })} className={inputClass} /></EditorField><button type="button" onClick={onRemove} className="text-left text-xs font-bold text-red-600"><Trash2 className="mr-2 inline size-4" /> Remove speaking activity</button></div>;
}
