import { useCallback, useEffect, useState } from 'react';
import { useFocusEffect, useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Button, Card, Copy, EmptyState, Eyebrow, Heading, InlineNotice, LoadingState, Screen } from '@/components/ui';
import { palette, radius, space } from '@/constants/theme';
import { createCustomLesson, loadGenerationStatus, loadLessonCreationState, loadProfile } from '@/lib/aiko-repository';
import type { JLPTLevel, LessonCreationState, Profile } from '@/types/domain';

const levels: JLPTLevel[] = ['N5', 'N4', 'N3', 'N2', 'N1'];
export default function LearnScreen() {
  const router = useRouter(); const [profile, setProfile] = useState<Profile | null>(null); const [path, setPath] = useState<LessonCreationState | null>(null); const [topic, setTopic] = useState(''); const [selectedLevel, setSelectedLevel] = useState<JLPTLevel>('N5'); const [requestId, setRequestId] = useState<string | null>(null); const [working, setWorking] = useState(false); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const [nextProfile, nextPath] = await Promise.all([loadProfile(), loadLessonCreationState()]); setProfile(nextProfile); setPath(nextPath); setSelectedLevel(nextProfile.current_jlpt_level); if (nextPath.requestId && nextPath.lessonState === 'building') setRequestId(nextPath.requestId); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Learn could not be loaded.'); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  useEffect(() => { if (!requestId) return; const timer = setInterval(() => { void loadGenerationStatus(requestId).then((status) => { const lessonId = typeof status.lessonId === 'string' ? status.lessonId : typeof status.lesson_id === 'string' ? status.lesson_id : null; if (lessonId) { clearInterval(timer); setWorking(false); setRequestId(null); router.push(`/lesson/${lessonId}`); } }).catch((cause) => { clearInterval(timer); setWorking(false); setError(cause instanceof Error ? cause.message : 'Lesson generation stopped.'); }); }, 3000); return () => clearInterval(timer); }, [requestId, router]);
  async function create() { setError(null); setWorking(true); try { const result = await createCustomLesson(topic.trim(), selectedLevel); const lessonId = typeof result.lesson_id === 'string' ? result.lesson_id : null; const nextRequest = typeof result.requestId === 'string' ? result.requestId : null; if (lessonId) router.push(`/lesson/${lessonId}`); else if (nextRequest) setRequestId(nextRequest); else throw new Error('AIko did not return a lesson request.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'AIko could not create this lesson.'); setWorking(false); } }
  if (loading && !profile) return <Screen scroll={false}><LoadingState label="Loading your lesson path…" /></Screen>;
  const resumableId = path?.resumeLessonId ?? (path?.lessonState === 'ready' ? path.lessonId : null); const premium = profile?.subscription_plan !== 'free';
  return <Screen><View style={styles.intro}><Eyebrow>Learn</Eyebrow><Heading>{premium ? 'Choose the story. AIko builds the lesson.' : 'Your next lesson, chosen for you.'}</Heading><Copy>{premium ? 'Give AIko a topic. Your level, target kanji, and grammar come from your progress.' : 'Free lessons follow your current level and do not require a topic choice.'}</Copy></View>
    {error && <InlineNotice tone="danger">{error}</InlineNotice>}
    {working || requestId ? <Card style={styles.building}><LoadingState label="AIko is creating your connected lesson…" /><Copy>Story and word support arrive first. The remaining activities prepare in the background.</Copy></Card> : null}
    {resumableId && !working ? <Card style={styles.resume}><Eyebrow>Unfinished lesson</Eyebrow><Text style={styles.title}>{path?.resumeTopic ?? 'Continue your lesson'}</Text><Copy>{path?.resumeLevel ?? profile?.current_jlpt_level} · Your completed sections stay saved.</Copy><Button label="Resume lesson" icon="arrow-forward" onPress={() => router.push(`/lesson/${resumableId}`)} /></Card> : null}
    {premium && !working ? <Card style={styles.form}><Text style={styles.label}>Topic</Text><TextInput value={topic} onChangeText={setTopic} placeholder="A quiet café on a rainy evening" placeholderTextColor={palette.inkMuted} maxLength={120} style={styles.input} /><Text style={styles.label}>Level</Text><View style={styles.levels}>{levels.map((item) => <Pressable key={item} onPress={() => setSelectedLevel(item)} style={[styles.level, item === selectedLevel && styles.levelSelected]}><Text style={[styles.levelText, item === selectedLevel && styles.levelTextSelected]}>{item}</Text></Pressable>)}</View><Button label="Create my lesson" icon="sparkles" onPress={create} disabled={topic.trim().length < 2 || !path?.canCreate} /><Copy>{path ? `${Math.max(0, path.dailyLimit - path.creationsToday)} creations remaining today.` : ''}</Copy></Card> : null}
    {!premium && !resumableId && !working ? <EmptyState title="Your level-matched lesson is being selected" detail="AIko uses your level and completed lessons. A lesson appears here when it is ready." /> : null}
  </Screen>;
}
const styles = StyleSheet.create({ intro: { gap: space.sm }, resume: { gap: space.md, borderColor: palette.moss200 }, form: { gap: space.md }, building: { minHeight: 360, gap: space.md }, title: { color: palette.ink, fontSize: 20, fontWeight: '800' }, label: { color: palette.ink, fontSize: 14, fontWeight: '800' }, input: { minHeight: 58, borderWidth: 1, borderColor: palette.line, borderRadius: radius.md, paddingHorizontal: space.lg, color: palette.ink, fontSize: 16, backgroundColor: palette.paper }, levels: { flexDirection: 'row', gap: space.sm }, level: { flex: 1, height: 44, borderRadius: radius.pill, borderWidth: 1, borderColor: palette.line, alignItems: 'center', justifyContent: 'center' }, levelSelected: { backgroundColor: palette.moss900, borderColor: palette.moss900 }, levelText: { color: palette.inkMuted, fontWeight: '800' }, levelTextSelected: { color: palette.white } });
