import { useEffect, useMemo, useState } from 'react';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { Button, Card, Copy, Eyebrow, InlineNotice, LoadingState } from '@/components/ui';
import { ListeningPlayer, SpeakingRecorder } from '@/components/lesson/audio-practice';
import { PracticeCard } from '@/components/lesson/practice-card';
import { StoryReader } from '@/components/lesson/story-reader';
import { palette, radius, space, type } from '@/constants/theme';
import { loadPlayableLesson, startOrResumeLesson } from '@/lib/aiko-repository';
import type { LessonPhase, PlayableLesson } from '@/types/domain';

const phaseOrder: LessonPhase[] = ['story', 'vocabulary', 'grammar', 'reading', 'listening', 'speaking'];
const labels: Record<LessonPhase, string> = { story: 'Story', vocabulary: 'Words & kanji', grammar: 'Grammar', reading: 'Reading', listening: 'Listening', speaking: 'Speaking' };

export default function LessonScreen() {
  const router = useRouter(); const { lessonId } = useLocalSearchParams<{ lessonId: string }>(); const [lesson, setLesson] = useState<PlayableLesson | null>(null); const [phaseIndex, setPhaseIndex] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [cached, setCached] = useState(false);
  useEffect(() => { if (!lessonId) return; let active = true; void loadPlayableLesson(lessonId).then(async (result) => { if (!active) return; setLesson(result.lesson); setCached(result.cached); await startOrResumeLesson(result.lesson); }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : 'This lesson could not be loaded.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [lessonId]);
  const phases = useMemo(() => lesson?.premiumPhaseAccess === 'full' ? phaseOrder : phaseOrder.filter((phase) => phase !== 'listening' && phase !== 'speaking'), [lesson?.premiumPhaseAccess]);
  if (loading) return <SafeAreaView style={styles.safe}><LoadingState label="Opening your lesson…" /></SafeAreaView>;
  if (!lesson || error) return <SafeAreaView style={styles.safe}><View style={styles.error}><InlineNotice tone="danger">{error ?? 'This lesson is unavailable.'}</InlineNotice><Button label="Return home" onPress={() => router.replace('/(tabs)')} /></View></SafeAreaView>;
  const phase = phases[Math.min(phaseIndex, phases.length - 1)]; const last = phaseIndex === phases.length - 1;
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable accessibilityLabel="Close lesson" onPress={() => router.replace('/(tabs)')} style={styles.close}><Ionicons name="close" size={25} color={palette.ink} /></Pressable><View style={styles.headerTitle}><Text style={styles.headerTopic}>{lesson.lesson.title}</Text><Text style={styles.headerPhase}>{labels[phase]}</Text></View><Text style={styles.count}>{phaseIndex + 1}/{phases.length}</Text></View>
    <View style={styles.progress}><View style={[styles.progressFill, { width: `${((phaseIndex + 1) / phases.length) * 100}%` }]} /></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.phaseRail}>{phases.map((item, index) => <Pressable key={item} onPress={() => setPhaseIndex(index)} style={[styles.phaseChip, index === phaseIndex && styles.phaseChipActive]}><Text style={[styles.phaseChipText, index === phaseIndex && styles.phaseChipTextActive]}>{labels[item]}</Text></Pressable>)}</ScrollView>
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>{cached && <InlineNotice tone="warning">You are reading the most recently saved copy. Progress will sync when the connection returns.</InlineNotice>}<PhaseContent lesson={lesson} phase={phase} /><View style={styles.actions}><Button label={last ? 'Return home' : `Continue to ${labels[phases[phaseIndex + 1]]}`} icon="arrow-forward" onPress={() => last ? router.replace('/(tabs)') : setPhaseIndex((value) => value + 1)} /></View></ScrollView>
  </SafeAreaView>;
}

function PhaseContent({ lesson, phase }: { lesson: PlayableLesson; phase: LessonPhase }) {
  if (phase === 'story') return <StoryReader title={lesson.lesson.title} japaneseTitle={lesson.lesson.japanese_title} lines={lesson.story} words={lesson.storyWords} />;
  if (phase === 'vocabulary' || phase === 'grammar') {
    const activities = lesson.practice.filter((item) => item.phase === phase);
    return <View style={styles.section}><View><Eyebrow>{labels[phase]}</Eyebrow><Text style={styles.sectionTitle}>{phase === 'vocabulary' ? 'Build recognition from the story.' : 'Use the patterns in context.'}</Text></View>
      {phase === 'grammar' ? <View style={styles.references}>{lesson.grammar.map((item) => <Card key={item.id} style={styles.reference}><Text style={styles.pattern}>{item.pattern}</Text><Text style={styles.referenceLabel}>STRUCTURE</Text><Text style={styles.structure}>{item.structure}</Text><Text style={styles.referenceLabel}>WHEN TO USE IT</Text><Copy>{item.usage_notes || item.meaning}</Copy><Text style={styles.referenceLabel}>EXAMPLE</Text><Text style={styles.example}>{item.example}</Text><Copy>{item.translation}</Copy></Card>)}</View> : null}
      {activities.map((item, index) => <PracticeCard key={item.id} index={index} total={activities.length} difficulty={item.difficulty} prompt={item.prompt} cue={item.cue} choices={item.choices ?? []} correctAnswer={item.correct_answer} explanation={item.explanation} hint={[item.hint_front, item.hint_back].filter(Boolean).join(' · ')} />)}
    </View>;
  }
  if (phase === 'reading') return <View style={styles.section}><View><Eyebrow>Reading</Eyebrow><Text style={styles.sectionTitle}>Read a new passage closely.</Text></View><Card><Text style={styles.readingJapanese}>{lesson.reading.map((line) => line.japanese_text).join(' ')}</Text><View style={styles.translation}><Eyebrow>English translation</Eyebrow><Copy>{lesson.reading.map((line) => line.translation).join(' ')}</Copy></View></Card>{lesson.readingQuestions.map((item, index) => <PracticeCard key={item.id} index={index} total={lesson.readingQuestions.length} difficulty={item.difficulty} prompt={item.question} choices={[]} correctAnswer={item.answer} />)}</View>;
  if (phase === 'listening') return <View style={styles.section}><View><Eyebrow>Listening</Eyebrow><Text style={styles.sectionTitle}>Listen for meaning.</Text></View>{lesson.listening.map((item, index) => <View key={item.id} style={styles.activityGroup}><ListeningPlayer text={item.transcript} audioAssetId={item.audio_asset_id} /><PracticeCard index={index} total={lesson.listening.length} difficulty={item.difficulty} prompt={item.prompt} choices={item.choices ?? []} correctAnswer={item.correct_answer} explanation={item.explanation} /></View>)}</View>;
  return <View style={styles.section}><View><Eyebrow>Speaking</Eyebrow><Text style={styles.sectionTitle}>Read each sentence aloud.</Text><Copy>AIko checks only the sentence match. Microphone access is requested when you start recording.</Copy></View>{lesson.speaking.map((item) => <SpeakingRecorder key={item.id} exerciseId={item.id} sentence={item.model_answer || item.prompt} />)}</View>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: palette.paper }, header: { minHeight: 64, paddingHorizontal: space.lg, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, close: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' }, headerTitle: { alignItems: 'center' }, headerTopic: { color: palette.inkMuted, fontSize: 11 }, headerPhase: { color: palette.ink, fontSize: 15, fontWeight: '800' }, count: { color: palette.moss700, fontSize: 12, fontWeight: '800', width: 42, textAlign: 'center' }, progress: { height: 4, backgroundColor: palette.line }, progressFill: { height: '100%', backgroundColor: palette.moss700 }, phaseRail: { gap: space.sm, paddingHorizontal: space.lg, paddingVertical: space.md }, phaseChip: { height: 34, paddingHorizontal: space.lg, borderRadius: radius.pill, backgroundColor: palette.moss100, justifyContent: 'center' }, phaseChipActive: { backgroundColor: palette.moss900 }, phaseChipText: { color: palette.inkMuted, fontSize: 11, fontWeight: '700' }, phaseChipTextActive: { color: palette.white }, content: { padding: space.xl, paddingBottom: 80, gap: space.xl }, section: { gap: space.xl }, sectionTitle: { color: palette.ink, fontFamily: type.display, fontSize: 29, lineHeight: 36, fontWeight: '700', marginTop: space.sm }, references: { gap: space.lg }, reference: { gap: space.md }, pattern: { color: palette.ink, fontFamily: type.japanese, fontSize: 27, fontWeight: '800' }, referenceLabel: { color: palette.inkMuted, fontSize: 10, fontWeight: '900', letterSpacing: 1.2, marginTop: space.sm }, structure: { color: palette.ink, fontSize: 14, fontWeight: '700', backgroundColor: palette.moss50, padding: space.md, borderRadius: radius.sm }, example: { color: palette.ink, fontFamily: type.japanese, fontSize: 18 }, readingJapanese: { color: palette.ink, fontFamily: type.japanese, fontSize: 20, lineHeight: 36, textAlign: 'justify' }, translation: { borderTopWidth: 1, borderTopColor: palette.line, paddingTop: space.lg, marginTop: space.xl, gap: space.sm }, activityGroup: { gap: space.md }, actions: { marginTop: space.lg }, error: { flex: 1, justifyContent: 'center', padding: space.xl, gap: space.xl } });
