create table if not exists public.custom_lesson_generation_traces (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.custom_lesson_requests(id) on delete cascade,
  stage text not null,
  event_type text not null,
  attempt integer not null default 1 check (attempt >= 1),
  model text,
  prompt text,
  raw_response text,
  response jsonb,
  issues text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists custom_lesson_generation_traces_request_created_idx
  on public.custom_lesson_generation_traces (request_id, created_at, id);

create index if not exists custom_lesson_generation_traces_event_idx
  on public.custom_lesson_generation_traces (event_type, created_at);

alter table public.custom_lesson_generation_traces enable row level security;

revoke all on table public.custom_lesson_generation_traces from anon;
revoke insert, update, delete on table public.custom_lesson_generation_traces from authenticated;
grant select on table public.custom_lesson_generation_traces to authenticated;

drop policy if exists "Learners can read their own generation traces"
  on public.custom_lesson_generation_traces;
create policy "Learners can read their own generation traces"
  on public.custom_lesson_generation_traces
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.custom_lesson_requests request
      where request.id = custom_lesson_generation_traces.request_id
        and request.user_id = auth.uid()
    )
  );

comment on table public.custom_lesson_generation_traces is
  'Durable debug history for custom lesson model responses, validation issues, repair prompts, repair responses, and transport retries.';
comment on column public.custom_lesson_generation_traces.prompt is
  'Exact prompt sent for this attempt, including the exact repair request when event_type is repair_response.';
comment on column public.custom_lesson_generation_traces.response is
  'Parsed structured JSON returned by the model.';
comment on column public.custom_lesson_generation_traces.raw_response is
  'Exact structured text returned by the model before JSON parsing.';
comment on column public.custom_lesson_generation_traces.issues is
  'Deterministic or validator issues found in this exact response.';
