"use client";

import { useMemo, useState } from "react";
import { Archive, Eye, ImageIcon, Link2, Save, Search, ShieldAlert, Unlink } from "lucide-react";
import { useAdminStore } from "@/store/admin-store";
import type { AssetStatus, ImageAsset } from "@/types/admin";
import type { JLPTLevel } from "@/types/lesson";
import { AdminEmptyState, AdminPageHeader, AdminSection, AdminStatus } from "@/components/admin/admin-primitives";
import { Button } from "@/components/ui/button";

export function ImageLibrary() {
  const assets = useAdminStore((state) => state.imageAssets);
  const save = useAdminStore((state) => state.saveImage);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<AssetStatus | "all">("all");
  const [special, setSpecial] = useState<"all" | "unused" | "reused" | "reported" | "missing">("all");
  const [editing, setEditing] = useState<ImageAsset | null>(null);
  const visible = useMemo(() => assets.filter((asset) => (!query || `${asset.description} ${asset.topicTags.join(" ")} ${asset.vocabularyTags.join(" ")}`.toLowerCase().includes(query.toLowerCase())) && (status === "all" || asset.status === status) && (special === "all" || (special === "unused" && asset.usageCount === 0) || (special === "reused" && asset.usageCount >= 3) || (special === "reported" && asset.status === "reported") || (special === "missing" && (!asset.description || !asset.topicTags.length)))), [assets, query, special, status]);
  return (
    <>
      <AdminPageHeader eyebrow="Asset operations" title="Image library" description="Manage reusable image metadata while keeping global asset quality separate from learner-specific freshness and image decay." />
      <div className="mb-5 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-[1fr_12rem_12rem]"><label className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input aria-label="Search images" value={query} onChange={(event) => setQuery(event.target.value)} className="admin-input pl-9" placeholder="Description, topic, or vocabulary" /></label><select aria-label="Image status" value={status} onChange={(event) => setStatus(event.target.value as AssetStatus | "all")} className="admin-input"><option value="all">All statuses</option>{["active", "review", "reported", "archived", "low quality", "inappropriate"].map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Image usage filter" value={special} onChange={(event) => setSpecial(event.target.value as typeof special)} className="admin-input"><option value="all">All usage</option><option value="unused">Unused</option><option value="reused">Highly reused</option><option value="reported">Reported</option><option value="missing">Missing metadata</option></select></div>
      <div className="grid gap-6 xl:grid-cols-[1fr_24rem]">
        <div>{visible.length ? <div className="grid gap-4 sm:grid-cols-2 2xl:grid-cols-3">{visible.map((asset, index) => <article key={asset.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><button type="button" onClick={() => setEditing(asset)} className={`grid h-44 w-full place-items-center ${index % 3 === 0 ? "bg-gradient-to-br from-teal-100 to-sky-100" : index % 3 === 1 ? "bg-gradient-to-br from-orange-100 to-amber-50" : "bg-gradient-to-br from-violet-100 to-slate-100"}`} aria-label={`Preview ${asset.id}`}><ImageIcon className="size-12 text-slate-400" /></button><div className="p-4"><div className="flex items-center justify-between gap-2"><strong className="text-sm">{asset.id}</strong><AdminStatus>{asset.status}</AdminStatus></div><p className="mt-2 min-h-10 text-sm text-slate-600">{asset.description || "Missing description"}</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><Metric label="Quality" value={`${asset.qualityScore}/100`} /><Metric label="Lesson usage" value={asset.usageCount} /><Metric label="Global usage" value={asset.globalUsageCount} /><Metric label="Learner freshness" value={`${asset.learnerFreshnessScore}/100`} /></div><div className="mt-4 flex gap-1"><Icon label="Edit metadata" onClick={() => setEditing(asset)}><Eye className="size-4" /></Icon><Icon label="Archive" onClick={() => save({ ...asset, status: "archived" })}><Archive className="size-4" /></Icon><Icon label="Mark inappropriate" onClick={() => save({ ...asset, status: "inappropriate" })}><ShieldAlert className="size-4" /></Icon><Icon label="Mark low quality" onClick={() => save({ ...asset, status: "low quality" })}><ImageIcon className="size-4" /></Icon></div></div></article>)}</div> : <AdminEmptyState title="No image assets" description="Change the filters or reset the deterministic admin data." />}</div>
        <AdminSection title={editing ? "Image metadata" : "Select an image"} description="Edit, replace placeholder metadata, and link or unlink lessons.">
          {editing ? <ImageForm asset={editing} onChange={setEditing} onSave={() => { save(editing); setEditing(null); }} /> : <p className="py-10 text-center text-sm text-slate-500">Choose an image card to inspect its metadata.</p>}
        </AdminSection>
      </div>
    </>
  );
}

function ImageForm({ asset, onChange, onSave }: { asset: ImageAsset; onChange: (asset: ImageAsset) => void; onSave: () => void }) {
  return <form className="space-y-3" onSubmit={(event) => { event.preventDefault(); onSave(); }}><Field label="Description"><textarea value={asset.description} onChange={(event) => onChange({ ...asset, description: event.target.value })} className="admin-input min-h-20 py-3" /></Field><Field label="Topic tags"><input value={asset.topicTags.join(", ")} onChange={(event) => onChange({ ...asset, topicTags: split(event.target.value) })} className="admin-input" /></Field><Field label="Visible objects"><input value={asset.visibleObjects.join(", ")} onChange={(event) => onChange({ ...asset, visibleObjects: split(event.target.value) })} className="admin-input" /></Field><Field label="Vocabulary tags"><input value={asset.vocabularyTags.join(", ")} onChange={(event) => onChange({ ...asset, vocabularyTags: split(event.target.value) })} className="admin-input" /></Field><Field label="Grammar compatibility"><input value={asset.grammarCompatibility.join(", ")} onChange={(event) => onChange({ ...asset, grammarCompatibility: split(event.target.value) })} className="admin-input" /></Field><Field label="Level"><select value={asset.level} onChange={(event) => onChange({ ...asset, level: event.target.value as JLPTLevel })} className="admin-input">{["N5", "N4", "N3", "N2", "N1"].map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Linked lesson IDs"><textarea value={asset.linkedLessonIds.join("\n")} onChange={(event) => onChange({ ...asset, linkedLessonIds: event.target.value.split("\n").map((item) => item.trim()).filter(Boolean), usageCount: event.target.value.split("\n").filter(Boolean).length })} className="admin-input min-h-20 py-3" /></Field><Field label="Status"><select value={asset.status} onChange={(event) => onChange({ ...asset, status: event.target.value as AssetStatus })} className="admin-input">{["active", "review", "reported", "archived", "low quality", "inappropriate"].map((item) => <option key={item}>{item}</option>)}</select></Field><Button type="submit" className="w-full rounded-xl"><Save className="size-4" /> Save metadata</Button><p className="flex items-center gap-2 text-xs text-slate-500">{asset.linkedLessonIds.length ? <Link2 className="size-4" /> : <Unlink className="size-4" />} {asset.linkedLessonIds.length} canonical lesson link(s)</p></form>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="field-label">{label}</span>{children}</label>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg bg-slate-50 p-2"><span className="block text-slate-400">{label}</span><strong>{value}</strong></div>; }
function Icon({ label, onClick, children }: { label: string; onClick: () => void; children: React.ReactNode }) { return <button type="button" aria-label={label} title={label} onClick={onClick} className="grid size-9 place-items-center rounded-lg text-slate-500 hover:bg-slate-100">{children}</button>; }
const split = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);
